package com.iflybank.demo.dao;


import com.iflybank.demo.model.Userinfo;
import org.apache.ibatis.jdbc.SQL;

public class UserinfoSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated
     */
    public String insertSelective(Userinfo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("userinfo");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=TINYINT}");
        }

        if (record.getAge() != null) {
            sql.VALUES("age", "#{age,jdbcType=INTEGER}");
        }

        if (record.getInfo() != null) {
            sql.VALUES("info", "#{info,jdbcType=VARCHAR}");
        }

        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Userinfo record) {
        SQL sql = new SQL();
        sql.UPDATE("userinfo");

        if (record.getAge() != null) {
            sql.SET("age = #{age,jdbcType=INTEGER}");
        }

        if (record.getInfo() != null) {
            sql.SET("info = #{info,jdbcType=VARCHAR}");
        }

        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }

        sql.WHERE("id = #{id,jdbcType=TINYINT}");

        return sql.toString();
    }
}
