spring:
  datasource:
    # JDBC 配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.31.200.107:9306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: atpcore
    password: 1qaz@WSX
    # 连接池配置
#    druid:
#      initial-size: 5
#      max-active: 20
#      min-idle: 5
#      max-wait: 60000

  server:
    8090